

class InvalidCharacterException(Exception):
    """\
    The InvalidCharacterException class. This exception is raised when an invalid character is read in from output.txt, the file generated by txt_creator.
    """
    pass